---
title: Vax Baltimore
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
email: your-email@domain.com
description: ''
baseurl:
url:
twitter_username: na
github_username: na
permalink: "/:title.html"
markdown: kramdown
excerpt_separator: "<!--more-->"
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock

# Server Config options
livereload: true     # You no longer need to include --livereload
